### ISSUE TITLE
version 0.2 not published

### ISSUE THREAD

**Issue by askeladd123** [jeraldamo/bevy_blender#1]
the readme mentions version 0.2 which is not on crates.io. if the library is stable, it would be great to have it in the registry

**Comment by jeraldamo** [comment]
I'm sorry this took so long to get to. I had personal life things and this was not a priority. I have published the latest version, which was with Bevy 0.7. I have also decided to mirror minor versions with Bevy (at least while Bevy is < 1.0), so the latest release was version 0.7 (not 0.2).

I will be working on migrating it so that all versions from 0.7 up to the current release have a working crates.io published package.

Once I have gotten there, I will start looking at new features.

Sorry again for the extreme delay.
